module.exports = {
  preset: 'jest-expo',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  testPathIgnorePatterns: ['/node_modules/'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
  },
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/index.ts',
    '!src/**/__tests__/**',
    '!src/theme/**',
    '!src/i18n/**',
    '!src/types/**',
    '!src/components/AppButton.tsx',
    '!src/components/AppCard.tsx',
    '!src/components/AppInput.tsx',
    '!src/components/AppLoadingScreen.tsx',
    '!src/components/AppScreen.tsx',
    '!src/components/SkeletonBlock.tsx',
    '!src/components/SkeletonText.tsx',
    '!src/components/MetricCard.tsx',
    '!src/components/EmptyState.tsx',
    '!src/components/StatusBadge.tsx',
    '!src/providers/AppProviders.tsx',
    '!src/providers/AuthProvider.tsx',
    '!src/providers/LocaleProvider.tsx',
    '!src/providers/WarehouseServiceProvider.tsx',
    '!src/features/common/screens/PlaceholderScreen.tsx',
    '!src/services/nfc/**',
    '!src/services/warehouse/createWarehouseService.ts',
    '!src/services/warehouse/types.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 75,
      lines: 75,
      statements: 75,
    },
  },
};
